{
    "identifiers": [
        "Reflection",
        "Runtime",
        "InteropServices",
        "Threading",
        "OpenRPA",
        "Store",
        "IAsyncResult",
        "AsyncCallback",
        "callback",
        "state",
        "callback",
        "callback",
        "state",
        "state",
        "thisLock",
        "state",
        "manualResetEvent",
        "manualResetEvent",
        "ThisLock",
        "manualResetEvent",
        "manualResetEvent",
        "ManualResetEvent",
        "isCompleted",
        "manualResetEvent",
        "completedSynchronously",
        "callback",
        "isCompleted",
        "thisLock",
        "completedSynchronously",
        "isCompleted",
        "InvalidProgramException",
        "completedSynchronously",
        "completedSynchronously",
        "completedSynchronously",
        "isCompleted",
        "ThisLock",
        "isCompleted",
        "manualResetEvent",
        "manualResetEvent",
        "callback",
        "callback",
        "e",
        "InvalidProgramException",
        "e",
        "completedSynchronously",
        "exception",
        "exception",
        "exception",
        "Complete",
        "completedSynchronously",
        "IAsyncResult",
        "result",
        "result",
        "CompletedSynchronously",
        "AsyncResult",
        "result",
        "AsyncState",
        "thisPtr",
        "GetNextCompletion",
        "completeSelf",
        "callback",
        "result",
        "e",
        "IsFatal",
        "e",
        "completeSelf",
        "completionException",
        "e",
        "completeSelf",
        "thisPtr",
        "Complete",
        "completionException",
        "exception",
        "exception",
        "exception",
        "OutOfMemoryException",
        "exception",
        "InsufficientMemoryException",
        "exception",
        "ThreadAbortException",
        "exception",
        "AccessViolationException",
        "exception",
        "SEHException",
        "exception",
        "TypeInitializationException",
        "exception",
        "TargetInvocationException",
        "exception",
        "exception",
        "InnerException",
        "AsyncCompletion",
        "callback",
        "nextAsyncCompletion",
        "callback",
        "AsyncResult",
        "asyncCompletionWrapperCallback",
        "AsyncResult",
        "asyncCompletionWrapperCallback",
        "AsyncCallback",
        "AsyncCompletionWrapperCallback",
        "AsyncResult",
        "asyncCompletionWrapperCallback",
        "nextAsyncCompletion",
        "nextAsyncCompletion",
        "result",
        "TAsyncResult",
        "IAsyncResult",
        "result",
        "TAsyncResult",
        "AsyncResult",
        "result",
        "ArgumentNullException",
        "result",
        "TAsyncResult",
        "asyncResult",
        "ArgumentException",
        "asyncResult",
        "endCalled",
        "InvalidOperationException",
        "asyncResult",
        "endCalled",
        "asyncResult",
        "isCompleted",
        "asyncResult",
        "AsyncWaitHandle",
        "WaitOne",
        "asyncResult",
        "manualResetEvent",
        "asyncResult",
        "manualResetEvent",
        "Close",
        "asyncResult",
        "exception",
        "asyncResult",
        "exception",
        "asyncResult",
        "AsyncCompletion",
        "IAsyncResult",
        "result"
    ],
    "literals": [
        "\"Async callback threw an Exception\"",
        "\"result\"",
        "\"Invalid AsyncResult\"",
        "\"result\"",
        "\"AsyncResult already ended\""
    ],
    "variables": [
        "AsyncCallback",
        "asyncCompletionWrapperCallback",
        "AsyncCallback",
        "callback",
        "completedSynchronously",
        "endCalled",
        "exception",
        "isCompleted",
        "ManualResetEvent",
        "manualResetEvent",
        "AsyncCompletion",
        "nextAsyncCompletion",
        "state",
        "thisLock",
        "AsyncState",
        "WaitHandle",
        "AsyncWaitHandle",
        "CompletedSynchronously",
        "HasCallback",
        "IsCompleted",
        "ThisLock",
        "AsyncResult",
        "thisPtr",
        "AsyncCompletion",
        "callback",
        "completeSelf",
        "completionException",
        "AsyncCompletion",
        "result",
        "TAsyncResult",
        "asyncResult"
    ],
    "comments": [
        "It's a bug to call Complete twice.",
        "If we completedSynchronously, then there's no chance that the manualResetEvent was created so",
        "we don't need to worry about a race",
        "These exceptions aren't themselves fatal, but since the CLR uses them to wrap other exceptions,",
        "we want to check to see whether they've been used to wrap a fatal exception.  If so, then they",
        "count as fatal.",
        "can be utilized by subclasses to write core completion code for both the sync and async paths",
        "in one location, signaling chainable synchronous completion with the boolean result,",
        "and leveraging PrepareAsyncCompletion for conversion to an AsyncCallback.",
        "NOTE: requires that \"this\" is passed in as the state object to the asynchronous sub-call being used with a completion routine."
    ],
    "docstrings": [],
    "functions": [
        "AsyncResult",
        "Complete",
        "Complete",
        "AsyncCompletionWrapperCallback",
        "IsFatal",
        "AsyncCallback",
        "PrepareAsyncCompletion",
        "AsyncCompletion",
        "GetNextCompletion",
        "TAsyncResult",
        "End"
    ],
    "classes": [
        "AsyncResult"
    ]
}